server:

  # configures the port that Eureka Server will be running
  port: 8080


spring:

  # DataSource Configuration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keylog?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: smd@12345

  # JPA Configurations
  jpa:
    #hibernate.ddl-auto: create
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true